### ISSUE TITLE
Outdated year references

### ISSUE THREAD

**Issue by KatherinePapcun** [TEALSK12/apcsa-public#82]
"As of the 2015–2016 school year, TEALS classes do not have access to the Practice-It dashboard for tracking student progress on the exercises."

"Since these materials are new in 2015–2016, TEALS will apply to have the new syllabus approved."

We're preparing for the 2018-19 school year, and seeing these two lines just made me realize that no one has updated the materials in 3 years.

**Comment by hollasch** [comment]
Thanks Katherine! Can you let us know where the text is that you're referring to?

**Comment by rachelhuang072** [comment]
It looks like both of these 2015-16 mentions are in the Introduction of the Gitbook. 

"Since these materials are new in 2015–2016, TEALS will apply to have the new syllabus approved." - About the AP Computer Science A Curriculum > paragraph 2

"As of the 2015–2016 school year, TEALS classes do not have access to the Practice-It dashboard for tracking student progress on the exercises." - Digital Tools Associated with This Curriculum > Practice-It! > paragraph 2
